### ISSUE TITLE
Exclude folders from being watched

### ISSUE THREAD

**Issue by trafium** [hanami/reloader#12]
I am attempting to integrate webpack into hanami app which uses hanami-reloader. 

My webpack configuration in development mode uses webpack-dev-server with hot module reloading, which triggers page reload on js source code changes. Since at the same time hanami-reloader triggers Rack restart, page reload triggered from webpack reloads the page while server is inaccessible and results in "This site can’t be reached" message from browser.  

Is it possible to somehow tell reloader to ignore file changes in specific folders? In my case I would exclude js source files handled by webpack so no Rack reload would trigger.

**Comment by adam12** [comment]
> Is it possible to somehow tell reloader to ignore file changes in specific folders?

This isn't currently possible. I'd suggest using [guard-rack](https://github.com/dblock/guard-rack) directly for now.
