### ISSUE TITLE
Could not find gem `guard-puma` when after `hanami new` on 2.0.0.rc1

### ISSUE THREAD

**Issue by janko** [hanami/reloader#19]
When I ran `hanami new blog`, `cd`'d into the project directory, and ran `hanami server`, I got:

```
Could not find gem 'guard-puma' in locally installed gems.
Run `bundle install` to install missing gems.      
```

The Gemfile contains that gem under `:development` group, so running `bundle install` fixed the issue. But the `hanami new` output said it already ran Bundler install, so I expected it to already install all the necessary gems.

**Comment by jodosha** [comment]
Fixed by https://github.com/hanami/reloader/pull/16
