### ISSUE TITLE
Glob patterns and improper regex in Guardfile

### ISSUE THREAD

**Issue by ellnix** [hanami/reloader#26]
## The lines
```ruby
watch(%r{config/*})
watch(%r{lib/*})
```
use glob pattern syntax inside a regex. 

For instance, the glob pattern `config/*` matches the string "config", followed by a "/", followed by any characters, which seems like the intended behavior. However `%r{}` defines a regex in ruby and the regex `config/*` matches the string "config" followed by 0 or more occurrences of "/".

Essentially these two lines are equivalent to searching for the strings "config" and "lib" respectively. You can verify this by making any file in the root of the app that contains the word "lib" or "config" (such as "liberty.txt") and seeing that when that file is saved, the server restarts.

## In addition, the `.+..+..+` pattern in
```ruby
watch(%r{app/templates/.+..+..+})
watch(%r{slices/.+/templates/.+..+..+})
```
will match:
- any character one or more times followed by
- any character followed by
- any character one or more times followed by
- any character followed by
- any character one or more times

Essentially, any 5 or more characters will match `.+..+..+`, since to match a literal `.` character in regex, you have to escape it `\.`

See [official Guardfile examples in the guard repository](https://github.com/guard/guard/wiki/Guardfile-examples).

**Comment by jodosha** [comment]
@ellnix Thanks for reporting this bug.

Would you mind manually testing https://github.com/hanami/reloader/pull/27 to see if it fixes the problem for you?
