### ISSUE TITLE
0.3.0 is not released on RubyGems

### ISSUE THREAD

**Issue by katafrakt** [hanami/reloader#9]
https://rubygems.org/gems/hanami-reloader - last version available on RubyGems is 0.2.1. This also makes instructions from readme result in an error

```
Fetching gem metadata from https://rubygems.org/.............
Fetching gem metadata from https://rubygems.org/.
Could not find gem 'hanami-reloader (~> 0.3)' in any of the gem sources listed in your Gemfile.
```

**Comment by cllns** [comment]
I just discovered this too

@jodosha Can you release 0.3.0 to rubygems, when you get a chance?

**Comment by jodosha** [comment]
Done. Thanks for pointing out. 👍
